"use client";

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { Input, Select, Textarea } from '../../../components/ui/Input';
import { Badge } from '../../../components/ui/Badge';
import { 
  Building2, ShieldCheck, FileText, ArrowRight, ArrowLeft, CheckCircle, 
  Sparkles, Upload, Image as ImageIcon, Check, Loader2, Eye, User, Trash2
} from 'lucide-react';

export default function NewListingWizardPage() {
  const router = useRouter();
  const [step, setStep] = useState<number>(1);
  const [propertyType, setPropertyType] = useState<string>('HDB');
  const [singpassModalOpen, setSingpassModalOpen] = useState<boolean>(false);
  const [verifyingSingpass, setVerifyingSingpass] = useState<boolean>(false);
  const [singpassVerified, setSingpassVerified] = useState<boolean>(false);

  // Form Details State
  const [title, setTitle] = useState<string>('');
  const [address, setAddress] = useState<string>('');
  const [price, setPrice] = useState<number>(760000);
  const [bedrooms, setBedrooms] = useState<number>(3);
  const [bathrooms, setBathrooms] = useState<number>(2);
  const [sizeSqft, setSizeSqft] = useState<number>(1205);
  const [tenure, setTenure] = useState<string>('99-year Leasehold');
  const [description, setDescription] = useState<string>('');
  const [autoEnhance, setAutoEnhance] = useState<boolean>(true);
  const [applyWatermark, setApplyWatermark] = useState<boolean>(true);
  const [fulfillment, setFulfillment] = useState<'diy' | 'agent'>('diy');
  const [selectedAgentId, setSelectedAgentId] = useState<string>('agent-3');

  // Photo uploads
  const [uploadedPhotos, setUploadedPhotos] = useState<string[]>([
    "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80"
  ]);
  const [uploadingMedia, setUploadingMedia] = useState<boolean>(false);

  // AI Description states
  const [aiGenerating, setAiGenerating] = useState<boolean>(false);

  // Comparable Transaction History (Fetched from HDB records on verification)
  const [comparables, setComparables] = useState<any[]>([]);

  // HDB details fetched from Singpass/MyInfo
  const [myInfoFlatDetails, setMyInfoFlatDetails] = useState<any>(null);

  // Trigger HDB MyInfo data load
  const triggerSingpassAuth = () => {
    setSingpassModalOpen(true);
  };

  const handleSingpassVerify = () => {
    setVerifyingSingpass(true);
    setTimeout(() => {
      setVerifyingSingpass(false);
      setSingpassVerified(true);
      setSingpassModalOpen(false);
      
      // Load verified HDB details
      const hdbRecord = {
        owner: "Samuel Tan Wei Ming",
        nric: "SXXXX789A",
        address: "Blk 211A Punggol Walk, #12-345, Singapore 821211",
        sizeSqm: 112,
        sizeSqft: 1205,
        flatType: "5-Room Improved HDB",
        remainingLease: 89,
        buildYear: 2016,
        district: 19,
        mrtStation: "Punggol MRT",
        mrtDistance: 250
      };

      setMyInfoFlatDetails(hdbRecord);
      setAddress(hdbRecord.address);
      setTitle(`High-Floor 5-Room flat at ${hdbRecord.address.split(',')[0]}`);
      setBedrooms(3);
      setBathrooms(2);
      setSizeSqft(hdbRecord.sizeSqft);
      setTenure("99-year Leasehold");

      // Load surrounding transactional comps
      setComparables([
        { block: "Blk 211A", unit: "#10-340", price: 755000, date: "May 2026", size: "1,205 sqft" },
        { block: "Blk 211B", unit: "#15-110", price: 775000, date: "Apr 2026", size: "1,205 sqft" },
        { block: "Blk 211A", unit: "#08-335", price: 745000, date: "Mar 2026", size: "1,180 sqft" },
        { block: "Blk 210C", unit: "#18-202", price: 790000, date: "Feb 2026", size: "1,205 sqft" }
      ]);

      // Trigger next step automatically
      setStep(3);
    }, 1500);
  };

  // AI Description Write
  const generateAiDescription = () => {
    setAiGenerating(true);
    setTimeout(() => {
      const generated = `[AI GENERATED BY AVA CO-PILOT]\nPremium high-floor ${bedrooms}-bedroom flat located in Punggol Walk. Spanning ${sizeSqft} sqft, this corner unit offers maximum privacy and cross-ventilation. Designed with a spatial density discipline, the layout is highly efficient with zero wasted corridor space.\n\nHighlights:\n- Verified owner listing, Singapore Citizen DIY post.\n- Just 250m to Punggol MRT and Waterway Point.\n- Under 1km to popular primary schools.\n- Pristine move-in condition. Ready for immediate previews.`;
      setDescription(generated);
      setAiGenerating(false);
    }, 1200);
  };

  const handleUploadPhotoMock = () => {
    setUploadingMedia(true);
    setTimeout(() => {
      setUploadedPhotos(prev => [
        ...prev,
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80"
      ]);
      setUploadingMedia(false);
    }, 1000);
  };

  const removeUploadedPhoto = (idx: number) => {
    setUploadedPhotos(prev => prev.filter((_, i) => i !== idx));
  };

  const handlePublishListing = () => {
    alert("Congratulations! Your listing has been published to V-RENT Marketplace.");
    router.push('/search');
  };

  return (
    <div className="max-w-3xl mx-auto py-6 space-y-8 text-left">
      
      {/* Wizard Progress Header */}
      <div className="space-y-4">
        <div className="flex justify-between items-center flex-wrap gap-4">
          <div>
            <h1 className="text-xl font-black uppercase tracking-wider text-foreground">List a Property</h1>
            <p className="text-xs text-neutral-500">Post your property directly on Singapore's PropTech Super Platform.</p>
          </div>
          <Badge variant="gold" className="text-[10px] font-black uppercase">Direct Owner Services</Badge>
        </div>

        {/* Custom Progress Steps */}
        <div className="flex items-center justify-between text-[10px] font-black uppercase text-neutral-400 border-t border-border pt-4">
          {[
            { s: 1, label: "Property Type" },
            { s: 2, label: "KYC Verification" },
            { s: 3, label: "Listing Specs" },
            { s: 4, label: "Fulfillment" },
            { s: 5, label: "Review & Publish" }
          ].map((item) => (
            <div key={item.s} className="flex items-center gap-1.5">
              <span className={`h-5 w-5 rounded-full flex items-center justify-center text-[9px] font-mono border ${
                step === item.s 
                  ? 'border-brand-gold bg-brand-gold/10 text-brand-gold font-extrabold scale-110' 
                  : (step > item.s ? 'border-emerald-500 bg-emerald-500/10 text-emerald-500' : 'border-neutral-700 text-neutral-500')
              }`}>
                {step > item.s ? <Check className="h-3 w-3" /> : item.s}
              </span>
              <span className={`hidden md:inline ${step === item.s ? 'text-brand-gold font-extrabold' : (step > item.s ? 'text-emerald-500' : '')}`}>
                {item.label}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* STEP 1: PROPERTY TYPE */}
      {step === 1 && (
        <Card className="p-6 space-y-6 animate-in fade-in duration-200">
          <h2 className="text-sm font-bold uppercase tracking-wider text-neutral-400">Select Property Category</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {[
              { id: 'HDB', title: 'HDB Resale Flat (Direct Owner)', desc: 'Official government verification loop for public housing listings.', icon: Building2, tag: 'Singpass Sync' },
              { id: 'Condo', title: 'Private Condominium', desc: 'Post private apartments, penthouses, or EC units.', icon: Building2 },
              { id: 'Landed', title: 'Landed Bungalow / Semi-D', desc: 'Freehold or leasehold houses and plots.', icon: Building2 },
              { id: 'Commercial', title: 'Commercial Vertical', desc: 'Offices, retail shophouses, or warehouse sublets.', icon: Building2 }
            ].map((cat) => {
              const Icon = cat.icon;
              const isSelected = propertyType === cat.id;
              return (
                <div
                  key={cat.id}
                  onClick={() => setPropertyType(cat.id)}
                  className={`p-4 border rounded-xl cursor-pointer transition-all flex flex-col justify-between h-40 ${
                    isSelected ? 'border-brand-gold bg-brand-gold/5' : 'border-border bg-card hover:bg-neutral-50/50 dark:hover:bg-neutral-900/10'
                  }`}
                >
                  <div className="flex justify-between items-start">
                    <div className="p-2.5 bg-neutral-100 dark:bg-neutral-900 border border-border text-brand-gold rounded-lg">
                      <Icon className="h-5 w-5" />
                    </div>
                    {cat.tag && <Badge variant="ai">{cat.tag}</Badge>}
                  </div>
                  <div>
                    <h3 className="text-xs font-black uppercase text-foreground mt-3">{cat.title}</h3>
                    <p className="text-[10px] text-neutral-500 mt-1 leading-normal">{cat.desc}</p>
                  </div>
                </div>
              );
            })}
          </div>
          <div className="flex justify-end pt-4">
            <Button 
              variant="gold" 
              rightIcon={<ArrowRight className="h-4 w-4" />} 
              onClick={() => {
                if (propertyType === 'HDB') {
                  setStep(2);
                } else {
                  // Skip Singpass verification loop for standard private listings
                  setStep(3);
                }
              }}
            >
              Continue to {propertyType === 'HDB' ? 'KYC Verification' : 'Specs'}
            </Button>
          </div>
        </Card>
      )}

      {/* STEP 2: KYC VERIFICATION (SINGPASS SYNC) */}
      {step === 2 && (
        <Card className="p-6 space-y-6 animate-in fade-in duration-200">
          <div className="text-center space-y-4 max-w-md mx-auto py-4">
            <div className="h-12 w-12 bg-red-500/10 rounded-full flex items-center justify-center text-red-500 border border-red-500/20 mx-auto">
              <ShieldCheck className="h-6 w-6" />
            </div>
            <h2 className="text-sm font-black uppercase tracking-wider text-foreground">Government Listing Verification</h2>
            <p className="text-xs text-neutral-400 leading-relaxed">
              Under Singapore CEA regulations, owners listing HDB resale properties directly must verify ownership records. Log in via Singpass to retrieve your verified property address and unit specifications.
            </p>
            <div className="pt-2">
              <Button 
                variant="gold" 
                className="w-full bg-red-600 hover:bg-red-700 text-white font-bold"
                onClick={triggerSingpassAuth}
              >
                🔒 Authenticate with Singpass
              </Button>
            </div>
          </div>

          <div className="flex gap-2 justify-between border-t border-border pt-4">
            <Button variant="outline" leftIcon={<ArrowLeft className="h-4 w-4" />} onClick={() => setStep(1)}>Back</Button>
            <Button variant="outline" rightIcon={<ArrowRight className="h-4 w-4" />} onClick={() => setStep(3)}>Skip Verification (Demo Mode)</Button>
          </div>
        </Card>
      )}

      {/* STEP 3: LISTING SPECIFICS */}
      {step === 3 && (
        <div className="space-y-6 animate-in fade-in duration-200">
          {/* Flat Verification Sync Banner */}
          {singpassVerified && myInfoFlatDetails && (
            <Card className="p-4 bg-emerald-500/5 border border-emerald-500/10 flex items-start gap-3">
              <CheckCircle className="h-5 w-5 text-emerald-400 mt-0.5 flex-shrink-0" />
              <div className="text-xs text-neutral-600 dark:text-neutral-400">
                <span className="font-bold text-foreground">Verified Ownership Record Connected</span>
                <p className="mt-0.5">Address: {myInfoFlatDetails.address}</p>
                <div className="flex flex-wrap gap-2 mt-1.5 text-[9px] uppercase tracking-wider font-mono">
                  <Badge variant="success">{myInfoFlatDetails.flatType}</Badge>
                  <Badge variant="secondary">Remaining Lease: {myInfoFlatDetails.remainingLease} yrs</Badge>
                  <Badge variant="secondary">Area: {myInfoFlatDetails.sizeSqm} sqm</Badge>
                </div>
              </div>
            </Card>
          )}

          {/* Pricing & Details Card */}
          <Card className="p-6 space-y-4">
            <h2 className="text-xs font-bold uppercase tracking-wider text-neutral-400 mb-2">1. Basic Specifications</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Input
                label="Asking Price (SGD)"
                type="number"
                required
                value={price}
                onChange={(e) => setPrice(Number(e.target.value))}
              />
              <Input
                label="Property Listing Title"
                type="text"
                required
                placeholder="e.g. Pristine High Floor Flat near MRT"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <Input
                label="Bedrooms"
                type="number"
                value={bedrooms}
                onChange={(e) => setBedrooms(Number(e.target.value))}
              />
              <Input
                label="Bathrooms"
                type="number"
                value={bathrooms}
                onChange={(e) => setBathrooms(Number(e.target.value))}
              />
              <Input
                label="Floor Size (sqft)"
                type="number"
                value={sizeSqft}
                onChange={(e) => setSizeSqft(Number(e.target.value))}
              />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-semibold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">Property Address</label>
              <input
                type="text"
                value={address}
                onChange={(e) => setAddress(e.target.value)}
                placeholder="e.g. Blk 211A Punggol Walk, Singapore 821211"
                className="w-full rounded-lg border border-border bg-card px-3.5 py-2 text-sm text-foreground focus:outline-none focus:border-brand-gold"
              />
            </div>
          </Card>

          {/* HDB Surrounding Comps Widget */}
          {singpassVerified && comparables.length > 0 && (
            <Card className="p-6 space-y-4">
              <div className="flex justify-between items-center pb-2 border-b border-border">
                <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-400">Surrounding Block Resale Transactions</h3>
                <span className="text-[9px] font-black text-brand-gold uppercase tracking-wider font-mono">HDB Database Sync</span>
              </div>
              <div className="divide-y divide-border text-xs">
                {comparables.map((comp, idx) => (
                  <div key={idx} className="py-2.5 flex justify-between items-center">
                    <div>
                      <span className="font-bold text-foreground">{comp.block} {comp.unit}</span>
                      <p className="text-[10px] text-neutral-400 mt-0.5">Sold on {comp.date} · {comp.size}</p>
                    </div>
                    <span className="font-bold text-foreground font-mono">SGD {comp.price.toLocaleString()}</span>
                  </div>
                ))}
              </div>
            </Card>
          )}

          {/* Description Card */}
          <Card className="p-6 space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-xs font-bold uppercase tracking-wider text-neutral-400">2. Rich Description</h2>
              <Button 
                size="sm" 
                variant="outline" 
                type="button"
                className="text-[10px] uppercase font-black tracking-wider text-brand-gold border-brand-gold/30"
                onClick={generateAiDescription}
                isLoading={aiGenerating}
                leftIcon={<Sparkles className="h-3.5 w-3.5" />}
              >
                AI Co-Pilot Compose
              </Button>
            </div>
            <Textarea
              rows={5}
              placeholder="Tell buyers about your property features, accessibility, schools..."
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </Card>

          {/* Media uploads & Enhancements */}
          <Card className="p-6 space-y-4">
            <h2 className="text-xs font-bold uppercase tracking-wider text-neutral-400">3. Media Uploads</h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
              {uploadedPhotos.map((p, idx) => (
                <div key={idx} className="relative rounded-lg overflow-hidden h-24 bg-neutral-100 border border-border group">
                  <img src={p} alt="Uploaded flat photo" className="h-full w-full object-cover" />
                  <button 
                    onClick={() => removeUploadedPhoto(idx)}
                    type="button"
                    className="absolute top-1 right-1 p-1 bg-red-600 hover:bg-red-700 rounded-md text-white cursor-pointer opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </button>
                </div>
              ))}
              <button
                onClick={handleUploadPhotoMock}
                type="button"
                className="rounded-lg border border-dashed border-neutral-700 bg-neutral-50/5 dark:bg-neutral-900/30 hover:bg-neutral-100 dark:hover:bg-neutral-900/50 flex flex-col items-center justify-center h-24 gap-1.5 transition-colors cursor-pointer text-neutral-400 hover:text-foreground text-[10px] font-bold"
                disabled={uploadingMedia}
              >
                {uploadingMedia ? (
                  <Loader2 className="h-4 w-4 animate-spin text-brand-gold" />
                ) : (
                  <>
                    <Upload className="h-4.5 w-4.5" />
                    <span>Upload Photo</span>
                  </>
                )}
              </button>
            </div>

            {/* Media enhancement toggles */}
            <div className="pt-2 grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div 
                onClick={() => setAutoEnhance(!autoEnhance)}
                className={`p-3.5 border rounded-xl cursor-pointer flex justify-between items-center transition-colors ${autoEnhance ? 'border-emerald-500 bg-emerald-500/5' : 'border-border'}`}
              >
                <div className="text-left text-xs">
                  <span className="font-bold text-foreground block">Auto-Enhance Photo Assets</span>
                  <span className="text-[9px] text-neutral-400">AI adjusts exposure, brightness & clarity.</span>
                </div>
                <div className={`h-4 w-4 rounded border flex items-center justify-center ${autoEnhance ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-neutral-500'}`}>
                  {autoEnhance && <Check className="h-3 w-3" />}
                </div>
              </div>

              <div 
                onClick={() => setApplyWatermark(!applyWatermark)}
                className={`p-3.5 border rounded-xl cursor-pointer flex justify-between items-center transition-colors ${applyWatermark ? 'border-emerald-500 bg-emerald-500/5' : 'border-border'}`}
              >
                <div className="text-left text-xs">
                  <span className="font-bold text-foreground block">V-RENT Secured Watermark</span>
                  <span className="text-[9px] text-neutral-400">Protects photos from fake-agent scraping.</span>
                </div>
                <div className={`h-4 w-4 rounded border flex items-center justify-center ${applyWatermark ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-neutral-500'}`}>
                  {applyWatermark && <Check className="h-3 w-3" />}
                </div>
              </div>
            </div>
          </Card>

          <div className="flex justify-between border-t border-border pt-4">
            <Button variant="outline" leftIcon={<ArrowLeft className="h-4 w-4" />} onClick={() => setStep(propertyType === 'HDB' ? 2 : 1)}>Back</Button>
            <Button variant="gold" rightIcon={<ArrowRight className="h-4 w-4" />} onClick={() => setStep(4)}>Continue</Button>
          </div>
        </div>
      )}

      {/* STEP 4: FULFILLMENT MODE */}
      {step === 4 && (
        <Card className="p-6 space-y-6 animate-in fade-in duration-200">
          <h2 className="text-sm font-bold uppercase tracking-wider text-neutral-400">Choose Listing Fulfillment Method</h2>
          
          <div className="space-y-4">
            {/* DIY Method */}
            <div 
              onClick={() => setFulfillment('diy')}
              className={`p-4 border rounded-xl cursor-pointer transition-all flex justify-between items-start gap-4 ${
                fulfillment === 'diy' ? 'border-brand-gold bg-brand-gold/5' : 'border-border'
              }`}
            >
              <div className="flex gap-3 text-xs text-left">
                <div className="h-8 w-8 bg-neutral-100 dark:bg-neutral-900 border border-border rounded flex items-center justify-center font-bold text-brand-gold">DIY</div>
                <div>
                  <span className="font-bold text-foreground block">Do-It-Yourself Direct Listing (FSBO)</span>
                  <p className="text-[10px] text-neutral-400 leading-normal mt-1 max-w-md">
                    Manage enquiries, handle physical tours, and receive offers directly via the V-RENT Secure Vault. S$0 listing fees.
                  </p>
                </div>
              </div>
              <input type="radio" checked={fulfillment === 'diy'} onChange={() => setFulfillment('diy')} />
            </div>

            {/* Agent-assisted Method */}
            <div 
              onClick={() => setFulfillment('agent')}
              className={`p-4 border rounded-xl cursor-pointer transition-all flex justify-between items-start gap-4 ${
                fulfillment === 'agent' ? 'border-brand-gold bg-brand-gold/5' : 'border-border'
              }`}
            >
              <div className="flex gap-3 text-xs text-left">
                <div className="h-8 w-8 bg-neutral-100 dark:bg-neutral-900 border border-border rounded flex items-center justify-center font-bold text-brand-gold">PRO</div>
                <div>
                  <span className="font-bold text-foreground block">Assign to a Verified Partner Agent</span>
                  <p className="text-[10px] text-neutral-400 leading-normal mt-1 max-w-md">
                    Let a professional partner broker handles photography, listings placement, and buyer viewings. Commission applies only on successful sale.
                  </p>
                </div>
              </div>
              <input type="radio" checked={fulfillment === 'agent'} onChange={() => setFulfillment('agent')} />
            </div>
          </div>

          {/* Roster of verified partner agents to select */}
          {fulfillment === 'agent' && (
            <div className="pt-4 space-y-3 border-t border-border">
              <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-400">Available District 19 Specialists</h3>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {[
                  { id: 'agent-3', name: 'Daniel Teo', rating: '4.95 (215 reviews)', bio: 'Top HDB Resale broker in Punggol.', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80' },
                  { id: 'agent-2', name: 'Sherry Tan', rating: '4.85 (98 reviews)', bio: 'Excellent customer satisfaction record.', image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150&q=80' },
                  { id: 'agent-1', name: 'Marcus Lim', rating: '4.90 (142 reviews)', bio: 'Prestige listings planning specialist.', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150&q=80' }
                ].map(ag => (
                  <div 
                    key={ag.id}
                    onClick={() => setSelectedAgentId(ag.id)}
                    className={`p-3 border rounded-xl text-left cursor-pointer transition-colors relative ${selectedAgentId === ag.id ? 'border-brand-gold bg-brand-gold/5' : 'border-border'}`}
                  >
                    <div className="flex gap-2 items-center">
                      <div className="h-8 w-8 rounded-full overflow-hidden flex-shrink-0">
                        <img src={ag.image} alt={ag.name} className="h-full w-full object-cover" />
                      </div>
                      <div className="text-[10px]">
                        <span className="font-bold text-foreground block">{ag.name}</span>
                        <span className="text-brand-gold block mt-0.5 font-bold">★ {ag.rating}</span>
                      </div>
                    </div>
                    <p className="text-[9px] text-neutral-400 mt-2 font-normal leading-normal truncate">{ag.bio}</p>
                    {selectedAgentId === ag.id && (
                      <span className="absolute top-2 right-2 text-brand-gold">
                        <CheckCircle className="h-4 w-4" />
                      </span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="flex justify-between border-t border-border pt-4">
            <Button variant="outline" leftIcon={<ArrowLeft className="h-4 w-4" />} onClick={() => setStep(3)}>Back</Button>
            <Button variant="gold" rightIcon={<ArrowRight className="h-4 w-4" />} onClick={() => setStep(5)}>Review & Preview</Button>
          </div>
        </Card>
      )}

      {/* STEP 5: REVIEW & PREVIEW */}
      {step === 5 && (
        <div className="space-y-6 animate-in fade-in duration-200">
          <h2 className="text-sm font-bold uppercase tracking-wider text-neutral-400">Review Draft Listing Card</h2>
          
          {/* Card Preview Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-start">
            {/* Listing Preview Card */}
            <div className="md:col-span-2">
              <Card className="p-0 overflow-hidden text-left border border-border">
                <div className="h-44 bg-neutral-100 overflow-hidden relative">
                  <img src={uploadedPhotos[0]} alt={title} className="h-full w-full object-cover" />
                  <div className="absolute top-2 left-2 flex gap-1">
                    <Badge variant="success">Verified Owner</Badge>
                    <Badge variant="gold">D{singpassVerified ? myInfoFlatDetails?.district : 19}</Badge>
                  </div>
                </div>
                <div className="p-5 space-y-4">
                  <div className="space-y-1">
                    <span className="text-[9px] font-black text-brand-gold uppercase tracking-wider block">
                      {propertyType} · {singpassVerified ? myInfoFlatDetails?.flatType : 'Direct Owner Listing'}
                    </span>
                    <h3 className="text-sm font-black text-foreground uppercase">{title || 'Untitled Listing'}</h3>
                    <p className="text-xs text-neutral-400 mt-0.5">{address || 'No address specified'}</p>
                  </div>

                  <div className="flex items-baseline gap-4">
                    <span className="text-lg font-black text-brand-gold">SGD {price.toLocaleString()}</span>
                    <span className="text-[10px] text-neutral-500 font-bold uppercase">{sizeSqft} sqft · S${Math.round(price/sizeSqft)} /psf</span>
                  </div>

                  <div className="grid grid-cols-3 text-center py-2 bg-neutral-50/50 dark:bg-neutral-900/30 rounded-lg text-[10px] text-neutral-500 font-bold uppercase tracking-wider border border-border">
                    <div>
                      <span className="block text-foreground font-black text-xs">{bedrooms}</span>
                      Bedrooms
                    </div>
                    <div>
                      <span className="block text-foreground font-black text-xs">{bathrooms}</span>
                      Bathrooms
                    </div>
                    <div>
                      <span className="block text-foreground font-black text-xs">{sizeSqft}</span>
                      Size sqft
                    </div>
                  </div>

                  <div className="space-y-1.5 pt-2">
                    <span className="text-[9px] font-black text-neutral-400 uppercase tracking-widest block">Description</span>
                    <p className="text-[11px] text-neutral-500 leading-normal normal-case font-normal">{description || 'No description written yet.'}</p>
                  </div>
                </div>
              </Card>
            </div>

            {/* Verification Stats / Roster Summary Panel */}
            <div className="space-y-4">
              <Card className="p-4 space-y-3 text-xs text-left">
                <span className="text-[9px] font-black text-neutral-400 uppercase tracking-wider block">Deployment Audit</span>
                <div className="space-y-2">
                  <div className="flex justify-between font-semibold border-b border-border pb-1.5">
                    <span>Listing Channel:</span>
                    <Badge variant="success">FSBO Feed</Badge>
                  </div>
                  <div className="flex justify-between font-semibold border-b border-border pb-1.5">
                    <span>Singpass KYC:</span>
                    <span>{singpassVerified ? '✅ VERIFIED' : '❌ PENDING'}</span>
                  </div>
                  <div className="flex justify-between font-semibold border-b border-border pb-1.5">
                    <span>Auto-Repost Mode:</span>
                    <span>Active (Daily)</span>
                  </div>
                  <div className="flex justify-between font-semibold">
                    <span>Fulfillment Route:</span>
                    <span className="uppercase text-brand-gold">{fulfillment} Mode</span>
                  </div>
                </div>
              </Card>

              {fulfillment === 'agent' && (
                <Card className="p-4 space-y-3 text-xs text-left border-dashed border-brand-gold/30">
                  <span className="text-[9px] font-black text-brand-gold uppercase tracking-wider block">Assigned Broker Agent</span>
                  <div className="flex items-center gap-2">
                    <div className="h-8 w-8 rounded-full bg-neutral-800 overflow-hidden flex-shrink-0">
                      <img src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80" alt="Daniel Teo" className="h-full w-full object-cover" />
                    </div>
                    <div>
                      <span className="font-bold text-foreground block">Daniel Teo</span>
                      <span className="text-[9px] text-neutral-400 block font-mono">CEA: R049281I</span>
                    </div>
                  </div>
                </Card>
              )}
            </div>
          </div>

          <div className="flex justify-between border-t border-border pt-4">
            <Button variant="outline" leftIcon={<ArrowLeft className="h-4 w-4" />} onClick={() => setStep(4)}>Back</Button>
            <Button variant="gold" rightIcon={<CheckCircle className="h-4 w-4" />} onClick={handlePublishListing}>Publish Listing to Feed</Button>
          </div>
        </div>
      )}

      {/* SINGPASS AUTH SIMULATOR MODAL */}
      {singpassModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md animate-in fade-in">
          <Card className="w-full max-w-sm p-6 space-y-6 text-center bg-white border border-neutral-200">
            {/* Header */}
            <div className="space-y-1">
              <span className="text-red-600 font-black text-xs tracking-widest uppercase">Singpass MyInfo Node</span>
              <h3 className="text-sm font-extrabold uppercase text-neutral-800 mt-1">Authenticate Identity & Ownership</h3>
            </div>

            {/* QR Mock */}
            <div className="p-4 border border-neutral-100 rounded-2xl max-w-[180px] mx-auto bg-neutral-50 shadow-inner">
              {verifyingSingpass ? (
                <div className="h-32 w-32 flex flex-col items-center justify-center text-xs gap-2 text-neutral-500 font-bold uppercase tracking-wider font-sans">
                  <Loader2 className="h-7 w-7 text-red-600 animate-spin" />
                  <span>Syncing...</span>
                </div>
              ) : (
                <div className="h-32 w-32 border-4 border-red-600 flex flex-col items-center justify-center text-[10px] text-red-600 font-black tracking-widest uppercase font-mono relative">
                  <span className="absolute -top-1.5 -left-1.5 bg-red-600 text-white p-0.5 text-[8px]">MOCK</span>
                  <div className="absolute top-2 left-2 right-2 bottom-2 bg-[radial-gradient(#b91c1c_2px,transparent_2px)] [background-size:8px_8px]" />
                  <span className="relative z-10 px-1 py-0.5 bg-white">SCAN QR</span>
                </div>
              )}
            </div>

            <p className="text-[10px] text-neutral-500 leading-normal max-w-xs mx-auto">
              Scan QR code using Singpass Mobile app or click below to simulate MyInfo data retrieval (Retrieves address, NRIC, HDB ownership).
            </p>

            <div className="flex gap-2">
              <Button 
                variant="outline" 
                className="flex-1 font-bold border-neutral-200 text-neutral-500 hover:bg-neutral-50"
                onClick={() => setSingpassModalOpen(false)}
              >
                Cancel
              </Button>
              <Button 
                variant="primary" 
                className="flex-1 bg-red-600 hover:bg-red-700 text-white font-bold"
                onClick={handleSingpassVerify}
                isLoading={verifyingSingpass}
              >
                Log In Demo
              </Button>
            </div>
          </Card>
        </div>
      )}

    </div>
  );
}
